# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: Docker@1
  inputs:
    command: Run an image
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: mongo:3.4-jessie
    ports: 27017:27017
  displayName: Run mongoDb instance

- script: |
    npm install
    npm run test
  displayName: 'npm install and build/test'
